'use client'

import { motion } from 'framer-motion'
import { MessageCircle, Zap, AlertCircle } from 'lucide-react'

const examples = [
  {
    question: '"what\'s overdue?"',
    answer: 'You have 2 overdue tasks: "review code" was due Apr 2 (2 days ago) and "finish project" was due Apr 3 (yesterday). Both are unlinked to a project.',
  },
  {
    question: '"what have I been working on?"',
    answer: 'This week you\'ve been primarily focused on LifeOS development. You completed Phase 3 implementation and have been logging daily standups. You also worked on your IITM research paper.',
  },
  {
    question: '"show me my mood trend"',
    answer: 'Your mood has been relatively stable this week with an average of 3.8/5. You had a dip on Thursday (2/5 - "tired but focused") but bounced back to 4/5 on Friday.',
  },
  {
    question: '"how many tasks did I complete?"',
    answer: 'You completed 8 tasks this week. Most completions were on Monday (3 tasks) and Friday (3 tasks). Your completion rate is up 20% compared to last week.',
  },
]

export default function ChatPage() {
  return (
    <div>
      <div className="badge" style={{ marginBottom: '20px' }}>Advanced</div>
      <h1 style={{
        fontSize: 'clamp(36px, 5vw, 48px)',
        fontFamily: 'Syne, sans-serif',
        marginBottom: '20px',
      }}>
        Chat Interface
      </h1>
      <p style={{
        color: 'var(--text-secondary)',
        fontSize: '18px',
        lineHeight: 1.8,
        marginBottom: '48px',
        maxWidth: '650px',
      }}>
        Ask natural language questions about your data. LifeOS uses AI to understand your context and provide intelligent answers.
      </p>

      <div style={{
        padding: '24px',
        background: 'var(--bg-secondary)',
        borderRadius: '12px',
        border: '1px solid var(--border-color)',
        marginBottom: '32px',
      }}>
        <h3 style={{
          fontSize: '14px',
          fontFamily: 'Syne, sans-serif',
          color: 'var(--text-dim)',
          textTransform: 'uppercase',
          letterSpacing: '1px',
          marginBottom: '16px',
        }}>
          Usage
        </h3>
        <code style={{
          fontFamily: 'IBM Plex Mono, monospace',
          fontSize: '14px',
          color: 'var(--accent-cyan)',
        }}>
          life chat "your question here"
        </code>
      </div>

      <h2 style={{
        fontSize: '24px',
        fontFamily: 'Syne, sans-serif',
        marginBottom: '24px',
      }}>
        Example Queries
      </h2>

      <div style={{ display: 'grid', gap: '20px', marginBottom: '48px' }}>
        {examples.map((example, i) => (
          <motion.div
            key={i}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.4, delay: i * 0.1 }}
            style={{
              padding: '24px',
              background: 'var(--bg-card)',
              border: '1px solid var(--border-color)',
              borderRadius: '12px',
            }}
          >
            <div style={{
              display: 'flex',
              alignItems: 'center',
              gap: '12px',
              marginBottom: '16px',
            }}>
              <MessageCircle size={18} style={{ color: 'var(--accent-amber)' }} />
              <code style={{
                fontFamily: 'IBM Plex Mono, monospace',
                fontSize: '14px',
                color: 'var(--accent-amber)',
              }}>
                {example.question}
              </code>
            </div>
            <p style={{
              color: 'var(--text-secondary)',
              fontSize: '15px',
              lineHeight: 1.7,
              marginLeft: '30px',
            }}>
              {example.answer}
            </p>
          </motion.div>
        ))}
      </div>

      <div style={{
        padding: '24px',
        background: 'var(--accent-cyan-dim)',
        borderRadius: '12px',
        border: '1px solid rgba(0, 229, 255, 0.2)',
      }}>
        <div style={{
          display: 'flex',
          alignItems: 'center',
          gap: '12px',
          marginBottom: '12px',
        }}>
          <AlertCircle size={18} style={{ color: 'var(--accent-cyan)' }} />
          <h3 style={{
            fontSize: '16px',
            fontFamily: 'Syne, sans-serif',
          }}>
            Note
          </h3>
        </div>
        <p style={{
          color: 'var(--text-secondary)',
          fontSize: '14px',
          lineHeight: 1.7,
        }}>
          Chat responses are generated by a local LLM (Qwen 2.5:7B) based on your data.
          Responses may vary based on the model&apos;s interpretation. For critical information,
          always verify against the actual data using <code style={{ color: 'var(--accent-cyan)', fontFamily: 'IBM Plex Mono, monospace' }}>life tasks</code> and <code style={{ color: 'var(--accent-cyan)', fontFamily: 'IBM Plex Mono, monospace' }}>life timeline</code>.
        </p>
      </div>
    </div>
  )
}